### ISSUE TITLE
Avaliação de vendedores

### ISSUE THREAD

**Issue by KevinCaio** [MC426-iFish/Projeto#18]
Como comprador (usuário) eu gostaria avaliar o pescador de quem comprei peixes recentemente. Além disso, preciso visualizar as avaliações dos vendedores de forma que eu consiga através de notas e comentários de outros usuários compradores avaliar se tal vendedor tem um bom atendimento e/ou produto.

Estimativa de esforço: 4/5

Critérios de aceitação:
- [x] Verifique se o usuário recebe a opção de avaliar o pescador ao comprar seu produto
- [x] Verifique se é possível ver as avaliações de cada vendedor

**Comment by brabesf** [comment]
As pull requests associadas à issue são: #51
