### ISSUE TITLE
Registro de compras

### ISSUE THREAD

**Issue by KevinCaio** [MC426-iFish/Projeto#19]
Como comprador (usuário) eu gostaria de visualizar as minhas compras anteriores de forma que eu tenha registrado as compras antigas e possa realizá-las novamente

Estimativa de esforço: 4/5

Critérios de aceitação:

- [x] Verifique se é possível ver o histórico de compras
- [x] Verifique se é possível comprar novamente o produto, se disponível

**Comment by brabesf** [comment]
Pull requests associados à issue: #40 #46
