### ISSUE TITLE
Trocar nome de usuário

### ISSUE THREAD

**Issue by RodrigoBZuiani** [MC426-iFish/Projeto#21]
Como usuário eu gostaria de poder alterar meu nome de usuário, a fim de corrigir eventuais erros ou em caso de troca de nome.

Estimativa de esforço: 1/5

Critérios de aceitação:
- [x] Verificar se qualquer usuário pode alterar seu nome público
- [x] Verificar se um email foi enviado confirmando a troca de nome

**Comment by brabesf** [comment]
As pull requests associadas à issue são: #55
