### ISSUE TITLE
Alterar senha

### ISSUE THREAD

**Issue by RodrigoBZuiani** [MC426-iFish/Projeto#22]
Como usuário eu gostaria de poder alterar minha senha em caso de esquecimento, invasão da conta ou para fortalecer minha segurança.

Estimativa de esforço: 2/5

Critérios de aceitação:
- [x] Verificar se o usuário consegue alterar sua senha
- [x] Garantir o funcionamento da criptografia utilizada para proteger as informações do usuário
- [x] Verificar o envio do email confirmando a troca de senha

**Comment by brabesf** [comment]
As pull requests associadas com a issue são: #55
